/// Apple identity provider (Sign in with Apple) for the Serverpod
/// authentication module (`serverpod_auth_idp`), with **nonce replay
/// protection**.
///
/// Ported from the official `serverpod_auth_idp_server` Apple provider so it is
/// a drop-in replacement, with the identity token's `nonce` claim verified
/// (the official provider hard-codes `nonce: null`).
///
/// Configure the provider via [AppleIdpConfig] (or
/// [AppleIdpConfigFromPasswords]) and expose [AppleIdpEndpoint] from your
/// server to enable Apple sign-in.
library;

export 'src/business/apple_idp.dart';
export 'src/business/apple_idp_admin.dart';
export 'src/business/apple_idp_config.dart';
export 'src/business/apple_idp_utils.dart'
    show AppleAccountDetails, AppleAuthSuccess, AppleIdpUtils;
export 'src/business/routes/apple_server_notification_route.dart';
export 'src/endpoints/apple_idp_endpoint.dart';

// Generated by `serverpod generate` — exposes the module Endpoints dispatcher
// (required so a host server can mount this module) + the [AppleAccount] model.
export 'src/generated/endpoints.dart';
export 'src/generated/protocol.dart';
